Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*_spec.rb'
